kind: PersistentVolume
apiVersion: v1
metadata:
  name: ebs-pv
  labels:
    type: amazonEBS
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0b8259315211962e1
    fsType: ext4