kind: PersistentVolume
apiVersion: v1
metadata:
  name: ebs-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
awsElasticBlockStore:
  volumeID: vol-01f27f8e7dccecc15
  fsType: ext4